name: Build Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        type: boolean
        default: false
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v1

    # - name: Restore artifacts, or setup vcpkg (do not install any package)
    #   uses: lukka/run-vcpkg@v10
    #   if: runner.os == "Windows"
    #
    - name: Install System Dependency
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get install libarchive-dev libgtk-3-dev
    # - name: Install System Dependency
    #   if: runner.os == 'Windows'
    #   run: |
    #     vcpkg install libarchive


    - name: tmate
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

    - name: Build
      if: runner.os == 'Windows'
      run: |
        cargo build --verbose --release --no-default-features
        echo "BINARY_PATH=./target/release/fmr.exe" >> $env:GITHUB_ENV

    - name: Build
      if: runner.os != 'Windows'
      run: |
        cargo build --verbose --release
        echo "BINARY_PATH=./target/release/fmr" >> $GITHUB_ENV

    - name: Strip
      run: |
        strip ${{ env.BINARY_PATH }}

    - uses: actions/upload-artifact@v3
      with:
        name: fmr-${{ runner.os }}
        path: |
          ${{ env.BINARY_PATH }}
